from django.shortcuts import render
from django.views import View

# Create your views here.
class InventoryHome(View):
    def get(self,request):
        return render(request,'inventory/home.html',{})

# Category.
class InventoryCategory(View):
    def get(self,request):
        return render(request,'inventory/category.html',{})
# Attribute.
class InventoryAttribute(View):
    def get(self,request):
        return render(request,'inventory/attribute.html',{})
# value.
class InventoryValue(View):
    def get(self,request):
        return render(request,'inventory/value.html',{})
# bundle.
class InventoryBundle(View):
    def get(self,request):
        return render(request,'inventory/bundle.html',{})
class InventoryItem(View):
    def get(self,request):
        return render(request,'inventory/item.html',{})
class InventorySupplier(View):
    def get(self,request):
        return render(request,'inventory/supplier.html',{})
class InventoryStore(View):
    def get(self,request):
        return render(request,'inventory/store.html',{})
class InventoryInv(View):
    def get(self,request):
        return render(request,'inventory/inventory.html',{})
class InventoryOrder(View):
    def get(self,request):
        return render(request,'inventory/order.html',{})
class InventoryUsers(View):
    def get(self,request):
        return render(request,'inventory/users.html',{})
class InventoryCheckout(View):
    def get(self,request):
        return render(request,'inventory/checkout.html',{})
class InventoryCreateCheckout(View):
    def get(self,request):
        return render(request,'inventory/createCheckout.html',{})
class InventoryPurchaseOrder(View):
    def get(self,request):
        return render(request,'inventory/purchaseOrder.html',{})
class InventoryCreatePurchaseOrder(View):
    def get(self,request):
        return render(request,'inventory/createpo.html',{})
class InventoryEditPurchaseOrder(View):
    def get(self,request):
        return render(request,'inventory/editpo.html',{})
class InventoryViewPurchaseOrder(View):
    def get(self,request):
        return render(request,'inventory/viewpo.html',{})
class InventoryCheckedIn(View):
    def get(self,request):
        return render(request,'inventory/checkin.html',{})
class InventoryOrderDetails(View):
    def get(self,request):
        return render(request,'inventory/orderdetails.html',{})
class InventoryServices(View):
    def get(self,request):
        return render(request,'inventory/services.html',{})
