# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.CharField(max_length=100)),
                ('attender_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('prposed_time', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('evaluator_note', models.CharField(blank=True, max_length=500, null=True)),
                ('cleaning_hours', models.FloatField(blank=True, default=0, null=True)),
                ('number_of_cleaners', models.IntegerField(blank=True, null=True)),
                ('estimated_price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('preffered_gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20, null=True)),
                ('quatation_status', models.CharField(blank=True, choices=[('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('ASK_FOR_DISCOUNT', 'ASK_FOR_DISCOUNT')], max_length=50, null=True)),
                ('payment_policy', models.CharField(blank=True, choices=[('ONE_TIME', 'ONE_TIME'), ('SUBSCRIPTION', 'SUBSCRIPTION'), ('DOWN_PAYMENT', 'DOWN_PAYMENT')], max_length=20, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('no_of_cleanings', models.IntegerField(blank=True, null=True)),
                ('no_of_down_payments', models.IntegerField(blank=True, null=True)),
                ('down_payment_deadend', models.DateTimeField(blank=True, null=True)),
                ('call_attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attender_evaluation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
