# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200427_1307'),
        ('evaluator', '0002_auto_20200427_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_note', models.CharField(blank=True, max_length=500, null=True)),
                ('estimated_cost', models.FloatField(blank=True, null=True)),
                ('cleaning_hours', models.FloatField(blank=True, null=True)),
                ('number_of_cleaners', models.IntegerField(blank=True, null=True)),
                ('fabric_type', models.CharField(blank=True, choices=[('SYNTHETIC', 'SYNTHETIC'), ('NATURAL', 'NATURAL')], max_length=20, null=True)),
                ('spot_stain_status', models.BooleanField()),
                ('size_of_carpet', models.CharField(blank=True, max_length=100, null=True)),
                ('piece_of_chairs', models.IntegerField(blank=True, null=True)),
                ('set_type', models.CharField(blank=True, choices=[('SMALL_SET', 'SMALL_SET'), ('MEDIUM_SET', 'MEDIUM_SET'), ('LARGE_SET', 'LARGE_SET')], max_length=20, null=True)),
                ('sanitization_type', models.CharField(blank=True, choices=[('SANITIZATION', 'SANITIZATION'), ('DISINFECTION', 'DISINFECTION'), ('STERILIZATION', 'STERILIZATION')], max_length=20, null=True)),
                ('size_to_be_sanitised', models.CharField(blank=True, max_length=100, null=True)),
                ('bed_type', models.CharField(blank=True, choices=[('SINGLE_BED', 'SINGLE_BED'), ('QUEEN_BED', 'QUEEN_BED'), ('KIND_BED', 'KIND_BED')], max_length=20, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_address', to='user.Address')),
                ('cleaning_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_cleaning_method', to='evaluator.CleaningMethod')),
                ('cleaning_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_cleaning_type', to='evaluator.CleaningType')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details', to='evaluator.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='evaluationdetails',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_location_type', to='evaluator.LocationType'),
        ),
        migrations.AddField(
            model_name='evaluationdetails',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_service_type', to='evaluator.ServiceType'),
        ),
    ]
