# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_auto_20200427_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='evaluation/')),
                ('media_type', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO')], max_length=20)),
                ('taken_status', models.CharField(choices=[('CUSTOMER_SEND', 'CUSTOMER_SEND'), ('AGENT_TAKEN', 'AGENT_TAKEN')], max_length=20)),
                ('evaluation_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.EvaluationDetails')),
            ],
        ),
    ]
