# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0008_auto_20200428_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('is_subscription', models.BooleanField()),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_gap', models.IntegerField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('no_of_cleanings', models.IntegerField(blank=True, null=True)),
                ('no_of_cleaning_completed', models.IntegerField(blank=True, null=True)),
                ('no_of_down_payments', models.IntegerField(blank=True, null=True)),
                ('no_of_down_payments_complete', models.IntegerField(blank=True, null=True)),
                ('down_payment_deadend', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_order', to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHECK', 'CHECK'), ('OTHER', 'OTHER')], max_length=100, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('check_no', models.CharField(blank=True, max_length=100, null=True)),
                ('check_date', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history_invoice', to='accountant.Invoice')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history_received_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
