# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_team_leader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTeamMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='cleaning/')),
                ('media_type', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO')], max_length=20)),
                ('taken_status', models.CharField(choices=[('BEFORE_CLEANING', 'BEFORE_CLEANING'), ('AFTER_CLEANING', 'AFTER_CLEANING')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_team_leader.CleaningTeam')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTeamMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='followuo/')),
                ('media_type', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('AUDIO', 'AUDIO')], max_length=20)),
                ('taken_status', models.CharField(choices=[('BEFORE_CLEANING', 'BEFORE_CLEANING'), ('AFTER_CLEANING', 'AFTER_CLEANING')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_team_leader.FollowUpTeam')),
            ],
        ),
    ]
