# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_team_leader', '0002_cleaningteammedia_followupteammedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTeamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(blank=True, max_length=500, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cleaning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_team_leader.CleaningTeam')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpTeamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(blank=True, max_length=500, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('followup_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_team_leader.FollowUpTeam')),
            ],
        ),
    ]
