# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('senior_team_leader', '0003_cleaningteamtask_followupteamtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningteamtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleaningteamtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cleaningteamtask',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='followupteamtask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followupteamtask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followupteamtask',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
