$(document).ready(function(){
$('#category-carousel').owlCarousel({
    loop:false,
    
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:4,
            nav:false
        },
        1000:{
            items:4,
            nav:false,
            loop:false
        }
    }
})
$('#service-carousel').owlCarousel({
    loop:false,
    
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:4,
            nav:false
        },
        1000:{
            items:4,
            nav:true,
            loop:false
        }
    }
})
})