# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluator', '0003_auto_20200427_1701'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20)),
                ('order_status', models.CharField(blank=True, choices=[('APPROVED_BY_CLIENT', 'APPROVED_BY_CLIENT'), ('CLEANING_TEAM_ASSIGNED', 'CLEANING_TEAM_ASSIGNED'), ('CLEANING_IN_PROGRESS', 'CLEANING_IN_PROGRESS'), ('CLEANING_FULFILLED', 'CLEANING_FULFILLED'), ('INVESTIGATION', 'INVESTIGATION'), ('INVESTIGATION_ASSIGNED', 'INVESTIGATION_ASSIGNED'), ('INVESTIGATION_IN_PROGRESS', 'INVESTIGATION_IN_PROGRESS'), ('INVESTIGATION_COMPLETED', 'INVESTIGATION_COMPLETED'), ('FOLLOW_UP_TEAM_ASSIGNED', 'FOLLOW_UP_TEAM_ASSIGNED'), ('FOLLOW_UP_CLEANING_IN_PROGRESS', 'FOLLOW_UP_CLEANING_IN_PROGRESS'), ('FOLLOW_UP_CLEANING_FULFILLED', 'FOLLOW_UP_CLEANING_FULFILLED'), ('ORDER_CLOSED', 'ORDER_CLOSED')], max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('DOWN_PAYMENT_PENDING', 'DOWN_PAYMENT_PENDING'), ('DOWN_PAYMENT_FULFILLED', 'DOWN_PAYMENT_PENDING_FULFILLED'), ('OUT_STANDING_PENDING', 'OUT_STANDING_PENDING'), ('OUT_STANDING_FULFILLED', 'OUT_STANDING_FULFILLED'), ('SUBSCRIPTION_PENDING', 'SUBSCRIPTION_PENDING'), ('SUBSCRIPTION_FULFILLED', 'SUBSCRIPTION_FULFILLED')], max_length=20, null=True)),
                ('instructions', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.Evaluation')),
            ],
        ),
    ]
